### ISSUE TITLE
'POINTNAVV1' should be removed in train_ppo.py

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/habitat-api#129]
Hi, it looks like that 'POINTNAVV1' has been removed in config_env. There is one left in train_ppo.py, https://github.com/facebookresearch/habitat-api/blob/969e85330c2a4868a3ec4ff345c306f05ec4c136/habitat_baselines/train_ppo.py#L131
It may be removed to avoid bugs:)

**Comment by mathfac** [comment]
Thank you for letting us know. @JasonJiazhiZhang can you take a look.

**Comment by erikwijmans** [comment]
Looks like it got re-introduced in https://github.com/facebookresearch/habitat-api/pull/89
