### ISSUE TITLE
Recursive directory lookup can take long

### ISSUE THREAD

**Issue by abhiskk** [facebookresearch/habitat-api#131]
This [line](https://github.com/facebookresearch/habitat-api/blob/master/setup.py#L38) looks for requirements.txt under all directories, this can be especially costly if you have data directories. 

One way to get around this is to only look at specific set of directories and ignore data directories.

**Comment by JasonJiazhiZhang** [comment]
@abhiskk What about looking only inside habitat_baselines (plus the main one)?

**Comment by abhiskk** [comment]
Yes, I think that should be good.
