### ISSUE TITLE
Update habitat version in docker

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/habitat-api#134]
Trying to use docker run the tutorial notebook, but get this:

> TypeError: get_config() got an unexpected keyword argument 'config_paths

I guess this error is because the old version of habitat in docker env

The habitat version in docker is 0.1.1

**Comment by abhiskk** [comment]
Yes the docker image is updated, in the meantime can you use the latest github versions of code.

**Comment by placeforyiming** [comment]
Will try soon, thanks!

**Comment by placeforyiming** [comment]
> Yes the docker image is updated, in the meantime can you use the latest github versions of code.

Wait, did you update in Docker Hub? Both two docker images are still updated several months ago

**Comment by placeforyiming** [comment]
Anyway, successfully installed by myself.
