### ISSUE TITLE
What should I do if I want to explore Replica-Dataset with habitat-api ?

### ISSUE THREAD

**Issue by placeforyiming** [facebookresearch/habitat-api#136]
Already can explore Replica with habitat-sim, so what should I do to use habitat-api on this dataset?

**Comment by abhiskk** [comment]
For working with the replica dataset you will have to generate episodes similar to the ones present in `val.json.gz` files for Matterport/Gibson (https://github.com/facebookresearch/habitat-api#task-datasets)

**Comment by placeforyiming** [comment]
See:

https://github.com/facebookresearch/habitat-api/issues/137

**Comment by Danmou** [comment]
> For working with the replica dataset you will have to generate episodes similar to the ones present in `val.json.gz` files for Matterport/Gibson (https://github.com/facebookresearch/habitat-api#task-datasets)

How would one generate these episodes? Is there a script used to generate episodes for Matterport and Gibson?
