### ISSUE TITLE
Add a fog of war to TopDownMap visualization

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-api#143]
We have [TopDownMap measure](https://github.com/facebookresearch/habitat-api/blob/master/habitat/tasks/nav/nav_task.py#L403) and [maps utils module](https://github.com/facebookresearch/habitat-api/blob/master/habitat/utils/visualizations/maps.py) to work with topdown maps.

As our trained agents doesn't have explicit scene map that's hard to understand what part of scene was actually seen by the agent. That would be great to implement a fog of war feature to our map visualization:
![image](https://user-images.githubusercontent.com/877440/60214830-255e8080-981b-11e9-9f30-f2c930b0a3d7.png)

Some options what exactly can be reflected:
- Visited agent's positions with some radius
- Seen part of the scene

**Comment by dhruvbatra** [comment]
This would be *awesome* to have!

**Comment by mathfac** [comment]
Adressed #160.
