### ISSUE TITLE
Can the agent move freely without collision with the environment?

### ISSUE THREAD

**Issue by weihaosky** [facebookresearch/habitat-api#157]
When the agent moves, it collides with the environment. Such that sometimes it does not move perfectly left when I command it to move left. Sometimes it is even stuck in one place and cannot move outside. How to let the agent move freely in the 3D space without collision with the environment? like a floating bodiless agent.
Many thanks!

**Comment by weihaosky** [comment]
solved

**Comment by erikwijmans** [comment]
You can add variants of the movement actions such that they only control the camera (as controls which only control the cameras currently have no collisions)  i.e. you re-register the `MoveRight` control with `body_action=False` and it'll only control the camera:

```
import habitat_sim
from habitat_sim.agent import default_controls

habitat_sim.register_move_fn(default_controls.MoveRight, name="camera_move_right", body_action=False)
```

then you can follow the following example to use those actions in the API: https://github.com/facebookresearch/habitat-api/blob/master/examples/new_actions.py

**Comment by weihaosky** [comment]
Thanks @erikwijmans ! But when the `body_action` is set to False, it seems the `MoveRight` is no longer `MoveRight`. It is moving to some strange direction. The original `MoveRight` with `body_action=True` is just moving along the x axis. This may be caused by the axis difference between the camera and body.

**Comment by weihaosky** [comment]
Oh, it seems this also happens for `body_action=True`. After the agent turns, the `MoveRight` still follows the original axis direction, which mean it is no longer a "moveright". How to let the agent move along the current right direction?

**Comment by erikwijmans** [comment]
Can you try using this branch on habitat-sim: https://github.com/facebookresearch/habitat-sim/tree/fix-move

That should fix the issue with `move_right` not moving in the correct coordinate frame.

**Comment by weihaosky** [comment]
Yes, change `absolute_transformation` to `transformation` works!

**Comment by weihaosky** [comment]
But when the camera moves away from the agent body, the turn_left or turn_right still rotates around the agent body rather than the camera.

**Comment by erikwijmans** [comment]
You’ll need to use `look_left` instead.

**Comment by weihaosky** [comment]
`look_left` will make the two cameras in a stereo structure rotate respectively. Thus after `look_left` it will no longer be stereo structure. So it `look_left` cannot be used in stereo camera.

**Comment by erikwijmans** [comment]
Given that you want to control a stereo pair, the body actions make more sense as that'll control a point in the middle of them.  You can disable collision checking by either setting `apply_filter` to false here: https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/agent/agent.py#L158 or commenting this loop: https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/simulator.py#L108-L109

**Comment by weihaosky** [comment]
Yeah! That's what I am looking for. Thanks man!

**Comment by mathfac** [comment]
Closing as resolved.
