### ISSUE TITLE
print  the current episode info in train_ppo.py 

### ISSUE THREAD

**Issue by kowshikthopalli** [facebookresearch/habitat-api#164]
## Relevant Code
while running https://github.com/facebookresearch/habitat-api/blob/master/habitat_baselines/train_ppo.py#L176 i.e.,
```
 envs = construct_envs(args)
```
followed by 
```
envs .current_episodes 
```
I expect to see the list of current episodes and their infos but unfortunately I dont see that. How do I access that info. TIA.

**Comment by erikwijmans** [comment]
`print(envs.current_episodes())`
