### ISSUE TITLE
Where to get data split for eqa task

### ISSUE THREAD

**Issue by lynl7130** [facebookresearch/habitat-api#202]
Hi, 

I want to use Habitat for ObjectGoal Navigation. 

Where could I get the data split of eqa (looks like object goals are provided) for Matterport3D? 

I see [this file](https://github.com/facebookresearch/habitat-api/blob/d69bf69cbc7afbd286583c2d5b8c2afb97cb1eb9/habitat/datasets/eqa/mp3d_eqa_dataset.py) uses the split from directory:

```
.../habitat-api/data/datasets/eqa
```

Thanks in advance!

**Comment by mathfac** [comment]
Hi @lynl7130, we are working on releasing those data files and plan to release it before 10-th of October. If you need any specific information right now as scene splits or object names list I can provide it.

**Comment by lynl7130** [comment]
Thank you @mathfac ! October 10 is nice. I would wait for your release.
