### ISSUE TITLE
Simulator reconfigure require different scene.

### ISSUE THREAD

**Issue by dexter1691** [facebookresearch/habitat-api#217]
## ❓ Questions and Help

https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator/habitat_simulator.py#L271

Why do we require the scene_id to be different when trying to reconfigure the Simulator? The current implementation doesn't cover cases where I might want to reconfigure the simulator on the fly with different actuation spec for the same scene.

**Comment by erikwijmans** [comment]
Looks like we didn't consider this case.  When swapping the scene, it makes sense to just kill the whole simulator and bring up a new one for that scene.

Does adding a
```python
else:
    self._sim.reconfigure(self.sim_config)
```
do it?

**Comment by dexter1691** [comment]
Yeah. That should fix it.
