### ISSUE TITLE
Plot multi-level rooms in matterport3D

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/habitat-api#227]
## ❓ Questions and Help

Am I correct that [this function](https://github.com/facebookresearch/habitat-api/blob/61af1b666bf082000280e407870fd42aa73da6a9/examples/shortest_path_follower_example.py#L37) currently only plots the trajectory of the agent within one level of the house?

Since there are some houses of multiple levels in matterport3d, is there a function that can handle multiple levels in one figure?

Thank you very much!

**Comment by erikwijmans** [comment]
We currently do not have such a function.
