### ISSUE TITLE
Only use Depth sensor to reproduce Sec.5 in publication?

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/habitat-api#229]
## ❓ Questions and Help

In the Sec.5 of Habitat publication, the best learning-based baseline is using depth only.

If we want to reproduce this result, shall we only use the "DEPTH_SENSOR" in the ppo_pointnav.yaml? I saw the current ppo_pointnav.yaml uses both RGB and DEPTH sensors.

Thank you!

**Comment by erikwijmans** [comment]
If you want to reproduce the results for the depth-only agent, yes, you should use only the depth sensor.
