### ISSUE TITLE
Should y and z axis be swapped in the aabb coordinate system?

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-api#23]
Author @vcartillier3:
It seems aabb coordinates should be swapped like [x, z, -y] to be consistent with the simulator coordinate system.
Or am I missing something?

**Comment by mathfac** [comment]
We don't do any coordinate swaps on HAPI (Habitat API) side. @msavva maybe you will be best person to answer the question.

**Comment by erikwijmans** [comment]
This should be fixed by https://github.com/facebookresearch/habitat-sim/pull/17
