### ISSUE TITLE
Semantics: Instance level -> 40-category level

### ISSUE THREAD

**Issue by lynl7130** [facebookresearch/habitat-api#230]
Hi,

I used to think d3_40_colors_rgb function as a method to translate the instance level annotation to 40-category level annotation. 
However, In Matterport3D, scene_id = 2azQ1b91cZZ, I see the following weird output from my semantic sensor:

<img width="512" alt="sem_bug" src="https://user-images.githubusercontent.com/26374350/67070647-a1742f80-f14e-11e9-9237-d1984ae30c76.png">

This is an output with d3_40_colors_rgb applied. You can see that every chair around the table has a different color, which does not make sense.

I followed exactly what you demonstrated in your tutorial, and I plotted out all of the object.catetory.index(), looks like all chairs are labeled '3' correctly.  

So how could I map instance-level labels to category-level labels?

Thanks in advance!

**Comment by erikwijmans** [comment]
The `d3_40_colors_rgb` is just for colorizing semantic or instance IDs.  The objects themselves can be used to creating the mapping
```python
object_id_to_class_id = {int(obj.id.split("_")[-1]): obj.category.index() for obj in scene.objects}
```

**Comment by lynl7130** [comment]
Problem solved, thank you!
