### ISSUE TITLE
Habitat RLEnv GPS observation frame of reference

### ISSUE THREAD

**Issue by PrieureDeSion** [facebookresearch/habitat-api#237]
Is there a way to get the ground-truth location of the agent for RLEnv? Adding the GPS_sensor gives a relative position w.r.t the start location as (0,0).

**Comment by erikwijmans** [comment]
You can add a new sensor like in this example: https://github.com/facebookresearch/habitat-api/blob/master/examples/register_new_sensors_and_measures.py#L45

**Comment by PrieureDeSion** [comment]
That looks perfect, I was extracting it by directly accessing the sim so far but this is very clean. Thanks :)
