### ISSUE TITLE
Cartesian angle to quaternion

### ISSUE THREAD

**Issue by stbook** [facebookresearch/habitat-api#243]
## ❓ Questions and Help
I was wondering if there is a function in habitat-api that can convert a cartesian angle into the corresponding quaternion angle?

**Comment by erikwijmans** [comment]
Habitat offers a number of quaternion utils: https://aihabitat.org/docs/habitat-sim/habitat_sim.utils.common.html

The wikipedia article on versors may also be useful: https://en.wikipedia.org/wiki/Versor
