### ISSUE TITLE
Instantiating multiple sensors of the same type

### ISSUE THREAD

**Issue by 5nefarious** [facebookresearch/habitat-api#250]
## ❓ Questions and Help
I'm trying to create a panoramic observation by stitching together multiple RGB sensors. However, it looks like the `RGBSensor` class initializes with a default uuid of `rgb`, and Habitat-Sim isn't allowing instantiation of multiple sensors with the same uuid. Is there a way to change the uuid in the config?

**Comment by bareblackfoot** [comment]
See habitat-api/examples/register_new_sensors_and_measures.py
