### ISSUE TITLE
Check failed: std::getenv("DISPLAY") != nullptr DISPLAY not detected in Habitat Api Demo in Jupyter Notebook

### ISSUE THREAD

**Issue by BryanBo-Cao** [facebookresearch/habitat-api#255]
Similar to the issue of https://github.com/facebookresearch/habitat-sim/issues/358.
But the difference is that when I run the [demo code](https://aihabitat.org/docs/habitat-api/habitat-api-demo.html) until
```
env = habitat.Env(config=config)
```
my kernel died and got the error messago of 
```
WindowlessContext.cpp:235] Check failed: std::getenv("DISPLAY") != nullptr DISPLAY not detected. For headless systems, compile with --headless for EGL support
*** Check failure stack trace: ***
```

**Comment by erikwijmans** [comment]
Closing in favor of https://github.com/facebookresearch/habitat-sim/issues/358  This is likely the exact same issue/cause
