### ISSUE TITLE
How to limit the agent on single-floor rooms?

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/habitat-api#258]
## ❓ Questions and Help
I found current MP3D dataset contains rooms with multi-floor rooms.

Is there any way to filter out multi-floor rooms, only keeping single-floor ones?

Thank you very much!

**Comment by chenwydj** [comment]
Could anyone lend some help? Thank you!

**Comment by erikwijmans** [comment]
In the case of MP3D, filtering to just single floor houses will likely leave very few remaining.  If you want to do that, you can use the semantic annotations to do that: https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator/habitat_simulator.py#L328

Alternatively, you can look into re-generating the navmeshes (the things that do collision checking/stair climbing/etc) with a lower agent climb angle (https://github.com/facebookresearch/habitat-sim/blob/master/src/esp/nav/PathFinder.h#L66).  Either using https://github.com/facebookresearch/habitat-sim/pull/333 or https://github.com/facebookresearch/habitat-sim/blob/master/src/utils/datatool/datatool.cpp

**Comment by chenwydj** [comment]
Thank you very much Erik!

**Comment by mathfac** [comment]
Closing as answered.
