### ISSUE TITLE
Baseline or benchmark for eqa?

### ISSUE THREAD

**Issue by xiaotaw** [facebookresearch/habitat-api#262]
## ❓ Questions and Help
Is there a baseline model of eqa, just like that of pointnav?

**Comment by mathfac** [comment]
@xiaotaw thank you for the question. Not yet, but most probably we will have some in the end of this quarter (May 2019).

**Comment by xiaotaw** [comment]
2020? : )

**Comment by mathfac** [comment]
yes, 2020.

**Comment by xiaotaw** [comment]
:+1:
