### ISSUE TITLE
Installation of Habitat-API 

### ISSUE THREAD

**Issue by vamsidesu5** [facebookresearch/habitat-api#269]
## ❓ Questions and Help

I'm currently trying to install habitat-api and run the example.py script. When I try to install habitat-api, I try running the example script using python examples/example.py and I received the following error: 

Traceback (most recent call last):
  File "examples/example.py", line 25, in <module>
    example()
  File "examples/example.py", line 11, in example
    env = habitat.Env(config=habitat.get_config("configs/tasks/pointnav.yaml"))
  File "/Users/vamsi/habitat-api/habitat/core/env.py", line 74, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/Users/vamsi/habitat-api/habitat/datasets/registration.py", line 16, in make_dataset
    assert _dataset is not None, "Could not find dataset {}".format(id_dataset)
AssertionError: Could not find dataset PointNav-v1

It seems that it cannot find the dataset in the habitat-api folder. I have been following the installation guide on the README and have placed the data in the correct folder(in habitat-api folder), but I still get this error. 

I have been using these instructions: https://github.com/facebookresearch/habitat-api#installation

Please let me know if I am missing something trivial or if there is another way go about this.

**Comment by wannabeOG** [comment]
Check issue #267. There is a conflict between the stable and the master version of the repository.

**Comment by mathfac** [comment]
@vamsidesu5, do you still have this issue? Can you `pip uninstall .` in habitat-api folder and check path of `habitat.__path__`? Thanks!

**Comment by mathfac** [comment]
Closing as the issue should be resolved.
