### ISSUE TITLE
top-down map visualization

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-api#27]
author @dhruvbatra:
Creating an issue so we don't forget. 

We should include top-down map visualization. 
v0: Static: showing just the occupied cells in the environment. Right now @abhiskk has a hacky solution, but in future this should be pulled in from habitat-sim. I created an issue there. 
https://github.com/fairinternal/habitat-sim/issues/105

v1: Dynamic: showing agent progress in the navigation episode. This can use a lot of code from #131. @mathfac has a preliminary version of this visualization. We should add a flag to indicate the target. 

v2: 3D top down map: like this 
https://sites.google.com/view/scene-memory-transformer

**Comment by dhruvbatra** [comment]
@StOnEGiggity -- we will be very happy to provide feedback and support for implementing this. You can also join our Slack to directly ask questions: 
https://aihabitat.org/#contact
