### ISSUE TITLE
Unable to run the example script

### ISSUE THREAD

**Issue by wannabeOG** [facebookresearch/habitat-api#273]
### Device Specifications

OS: Ubuntu 18.04
GPU: NVIDIA Geforce 1050ti, Driver Version: 390.129
CUDA 9.0

### Steps to reproduce the error

1. Followed the instructions detailed in the README to build the repository
2. Executed the command ``python examples/example.py``

### Error Message

2020-01-08 22:12:34,660 Initializing dataset PointNav-v1
2020-01-08 22:12:34,817 initializing sim Sim-v0
Platform::WindowlessGlxContext: no supported framebuffer configuration found
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0108 22:12:34.846784 19305 WindowlessContext.cpp:201] Check failed: glxCtx_.isCreated() [GLX] Failed to created headless glX context
*** Check failure stack trace: ***
[1]    19305 abort (core dumped)  python examples/example.py

Any help would be greatly appreciated

**Comment by erikwijmans** [comment]
Closing in favor of https://github.com/facebookresearch/habitat-sim/issues/417
