### ISSUE TITLE
Loading validation dataset for Gibson

### ISSUE THREAD

**Issue by Toraudonn** [facebookresearch/habitat-api#276]
## ❓ Questions and Help

When I tried to load `val_mini` split of the gibson dataset, the navmesh file of the episode was set to `/habitat-challenge-data/gibson/Greigsville.glb` instead of `data/scene_datasets/gibson/Greigsville.glb`.
I know that I can create my own pointnav dataset using [this code](https://github.com/facebookresearch/habitat-api/blob/master/habitat/datasets/pointnav/pointnav_generator.py), but I was wondering how you created train/val/val_mini/test for mp3d and gibson dataset.

**Comment by erikwijmans** [comment]
`val_mini` exists solely for the habitat challenge to verify that your model runs as expected on the evaluation server and is not setup to be (and shouldn't be) used for anything else, that is why it doesn't load correctly.  The train/val (and test for mp3d, test for Gibson is not public) datasets should load correctly and are the ones you should use.  Let us know if you are having issues with any of those!
