### ISSUE TITLE
Bug in evaluation

### ISSUE THREAD

**Issue by saketd403** [facebookresearch/habitat-api#279]
## 🐛 Bug

When I run the eval in run.py, I get the following error message.

## Command
python -u habitat_baselines/run.py --exp-config habitat_baselines/config/pointnav/ppo_pointnav.yaml --run-type eval
## To Reproduce

1.python -u habitat_baselines/run.py --exp-config habitat_baselines/config/pointnav/ppo_pointnav.yaml --run-type eval
2.
3.

  File "/nfs/stak/users/desaisau/desaisau/anaconda3/lib/python3.7/site-packages/habitat/utils/visualizations/utils.py", line 152, in draw_collision
    view[mask] = (alpha * np.array([255, 0, 0]) + (1.0 - alpha) * view)[mask]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 512 but corresponding boolean dimension is 256

## Expected behavior

Expected to get validation resuts

**Comment by mukulkhanna** [comment]
@saketd403 I was experiencing the same error. Were you able to figure out a solution?

I got it to work by commenting this [line](https://github.com/facebookresearch/habitat-api/blob/85b7907e8f4c7aa3904e6f9da6cf2aabcdcff742/habitat/utils/visualizations/utils.py#L151), but I am sure there would be a better way.
