### ISSUE TITLE
Top-down orthographic ﬂoorplan

### ISSUE THREAD

**Issue by pbw-Berwin** [facebookresearch/habitat-api#3]
Can we obtain the orthographic floorplan from the Habitat environment?

**Comment by mathfac** [comment]
Thank for the request. This functionality is in planned to be released. Multiple floors existence brings ambiguity to the task.
Worthwhile you can sample navigable points in the house and plot them. That can be considered as approximation of the floorplan.

**Comment by xcyan** [comment]
@mathfac What's the timeline for releasing this feature? Thanks!

**Comment by abhiskk** [comment]
I will put together an initial version for this and share here soon, this should be enough to help you in visualization.

**Comment by erikwijmans** [comment]
These changes have landed: https://github.com/facebookresearch/habitat-api/blob/master/habitat/utils/visualizations/maps.py

**Comment by mathfac** [comment]
Closing as functionality is already in master.
