### ISSUE TITLE
Rename LookLeft and LookRight to RotateLeft and RotateRight

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-api#30]
Author @danielgordon10:
https://github.com/fairinternal/habitat-sim/blob/439d586b8c643fd42f53a31a4b15a65af3e39bcf/src/esp/scene/ObjectControls.cpp#L46

Rotate is a better description of what's actually happening since the entire agent body is being rotated along with the camera.
Based on my understanding of previous conversations, we would __not__ want to change lookUp and lookDown to rotate.

This change will have to be synced with one on habitat-api to similarly rename things.

From @dhruvbatra 

> -- "look right/left" --> "turn right/left"? Because after "looking" semantics of "forward" don't necessarily change, but after "turning" they do.

**Comment by erikwijmans** [comment]
I believe this is done
