### ISSUE TITLE
Using pre-trained models with habitat_baselines

### ISSUE THREAD

**Issue by PrieureDeSion** [facebookresearch/habitat-api#300]
How does one use the pre-trained models (linked [here](https://github.com/facebookresearch/habitat-api/tree/master/habitat_baselines)) with the habitat_baselines `run.py` script?

Just treating them as eval checkpoints does not seem to be the right way due to the difference in structure. Adding a EVAL.USE_CKPT_CONFIG seems like the right way to go ahead, but there also seem to be conflicts in the policy architecture (the policy changed and has `visual_encoder` and `state_encoder` now.
Are there pre-trained models compatible with the current infrastructure?

**Comment by PrieureDeSion** [comment]
As a temporary fix, I modified the keys in the state_dict to reflect the changes in name (assuming the structure of the Policy network has remained unchanged otherwise).
Yet, the pre-trained model looks pretty bad and has definitely not been loaded right (attached some rollout videos).

![ezgif-2-e4693a47a2e0](https://user-images.githubusercontent.com/14254187/74822259-b4903b00-52b9-11ea-85d6-e6ffdc7fd736.gif)
![ezgif-2-16c108cf7439](https://user-images.githubusercontent.com/14254187/74822266-b659fe80-52b9-11ea-9bdf-6e6c791c123b.gif)

**Comment by erikwijmans** [comment]
The actions have change what number they are on, here is a little script I made to fix the checkpoints; https://gist.github.com/erikwijmans/94f33461982ac9e3cc354fb26e4b80e1

**Comment by PrieureDeSion** [comment]
@erikwijmans is there information on how the pre-trained baselines were trained, i.e. on Gibson or MP3D training split etc.?

**Comment by erikwijmans** [comment]
On Gibson.
