### ISSUE TITLE
Is that possible to pre-store all visual features in the disk

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/habitat-api#306]
## ❓ Questions and Help
Hi, is that possible to extract visual feature like R2R navigation task(https://github.com/peteanderson80/Matterport3DSimulator#precomputing-resnet-image-features)?

I am unfamiliar with VLN. Is that faster if we save all features? We can also save memory.

**Comment by erikwijmans** [comment]
Storing all-possible visual features to disk is not possible.  The state space in habitat-sim is infinite (as opposed to the Matterport3D simulator, where it is finite as you are constrained to a graph).
