### ISSUE TITLE
How to accuess all reachable positions within a Gibson dataset for a habitat agent?

### ISSUE THREAD

**Issue by AAdeleye** [facebookresearch/habitat-api#315]
## ❓ Questions and Help
Hello,

This question was addressed partially [here](https://github.com/facebookresearch/habitat-api/issues/261#issue-530931396) but I had a follow up question. 

Is it possible to access a list of reachable positions within a scene. 
For instance, if I load "Andover", rather than move randomly through the environment to generate images that I can save, I would want to loop over a list of coordinates. That way I have some confidence that images of the environment are at every room. I know the .jason.gz files contain random start positions. Would this be the best way to achieve this?

Also, for the files in the PointNav dataset for Gibsion. I was wondering if the .jason.gz files start positions are all on the first floor? (for a robot that can't go up stairs)  

Thank you.

**Comment by erikwijmans** [comment]
Relevant: https://github.com/facebookresearch/habitat-sim/pull/483

There isn't a list of reachable locations, the navigation space is infinite.  The PR linked above does a uniform sampling of locations over a floor.

**Comment by AAdeleye** [comment]
Thank you, that worked well. 

I know the code is still being updated but A few of the scenes, at least in the Gibson Dataset, have more distortion that I thought. 
![diningroom_habitat](https://user-images.githubusercontent.com/9774995/78058963-f511b880-733d-11ea-9d76-b26a51afc066.png)
![bathrom_habitat](https://user-images.githubusercontent.com/9774995/78058980-fc38c680-733d-11ea-9498-ff26dac5d65d.png)

It doesn't seem to be impact my network too much but I was wondering if this is to be expected?
Thanks -I will close after this since it's diverging a bit.

**Comment by dhruvbatra** [comment]
Yes, that is the data. Habitat doesn't create the data, we just render/simulate it. You can read about our quality annotations in our ICCV19 paper.
