### ISSUE TITLE
Integration tests: habitat-sim + habitat-api + baseline tests

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-api#32]
Implement test that will assure that whole stack: habitat-sim + habitat-api + baseline tests is working as expected.
Something similar to https://github.com/fairinternal/habitat-api/blob/master/test/test_baseline_agents.py, but more sophisticated.

**Comment by erikwijmans** [comment]
@mathfac -- Is this done with the CI in place?

**Comment by mathfac** [comment]
Solved with https://github.com/facebookresearch/habitat-api/pull/97.

**Comment by mathfac** [comment]
#97
