### ISSUE TITLE
Access Denied to pointnav_gibson_v2.zip.

### ISSUE THREAD

**Issue by tommyz94** [facebookresearch/habitat-api#323]
When I try to download pointnav_gibson_v2.zip I get an access denied error. Does it happen to others too?

The link is the one reported in the readme, this [one](https://dl.fbaipublicfiles.com/habitat/data/datasets/pointnav/gibson/v2/pointnav_gibson_v2.zip).

And the error obtained is the following:
```xml
<Error>
   <Code>AccessDenied</Code>
   <Message>Access Denied</Message>
   <RequestId>F4C43D09D4615289</RequestId>
   <HostId>   
     540nv3EQUrgcw+rw3MIGVs89Ah4Tdq1c6MQEI1l1H116wtN2n5nWfQdHL+QiAC/FMKT9wAANTEA=
   </HostId>
</Error>
```

**Comment by mathfac** [comment]
@tommyz94, thank you for reporting. Should be fixed now.
