### ISSUE TITLE
How to align depth sensor and semantic sensor?

### ISSUE THREAD

**Issue by lynl7130** [facebookresearch/habitat-api#329]
## How to align depth sensor and semantic sensor?

Hi, my task request sophisticated alignment between semantic sensor output and depth sensor output. However, currently habitat's two sensors are not aligned. 
The image attached is an example:
![image](https://user-images.githubusercontent.com/26374350/76401704-b4370d00-6358-11ea-838d-73b008b7d7b6.png)

Is there a way for me to get aligned outputs of these sensors? Thanks in advance!

**Comment by lynl7130** [comment]
Changing the rendering mesh [here](https://github.com/facebookresearch/habitat-sim/blob/171793312525155084393f0ea16c668ea354a6da/habitat_sim/simulator.py#L399-L406) solved my problem!

**Comment by ethanabrooks** [comment]
@lynl7130 could you say what you changed exactly?
