### ISSUE TITLE
Getting room label with MP3D dataset

### ISSUE THREAD

**Issue by rrwiyatn** [facebookresearch/habitat-api#331]
Hi, Is there a way to get room label from the Matterport 3D dataset with Habitat API? I would like to query which room the agent is in at every time step. Thanks!

**Comment by erikwijmans** [comment]
You can get the semantic annotations here: https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator/habitat_simulator.py#L358 (https://aihabitat.org/docs/habitat-sim/habitat_sim.scene.SemanticScene.html#regions).  Then use the bounding boxes for each region to determine which one the agent is in.

**Comment by rrwiyatn** [comment]
Okay will try that, thanks!
