### ISSUE TITLE
Import collision with openai baselines and habitat-api baselines

### ISSUE THREAD

**Issue by danielgordon10** [facebookresearch/habitat-api#34]
## Steps to reproduce
1. Clone https://github.com/openai/baselines
1. Add to pythonpath
1. Try and import it

## Observed Results

  * Imports habitat-api baseline

## Expected Results

  * I want to be able to import either of them. Probably this means renaming baselines to something else or putting it in a subdir somewhere.

**Comment by mathfac** [comment]
We discovered that issue as well. Try to install habitat-api without `-e` flag. `baselines` folder is mapped in `pythonpath`as it located in `habitat-api` folder.
