### ISSUE TITLE
Error when running the DD-PPO baseline with "train_encoder: False"

### ISSUE THREAD

**Issue by rosanom** [facebookresearch/habitat-api#368]
I'm trying to train the DD-PPO baseline after setting the `train_encoder` parameter to `False` and I get the following error:
<pre>
habitat_baselines/rl/ddppo/algo/ddppo_trainer.py&quot;, in train
    batch[&quot;visual_features&quot;] = self._encoder(batch)
...
habitat_baselines/rl/ddppo/policy/resnet_policy.py&quot;, in forward
    x = self.backbone(x)

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor)
should be the same
</pre>
I temporarily fixed moving the encoder on the cpu, but performances obviously drops instead of increasing.
More details: I'm loading the public pre-trained depth model with a resnet50 backbone.

Thanks

**Comment by erikwijmans** [comment]
This should be fixed on master -- can you check on master?
