### ISSUE TITLE
Does this include the physical engine？

### ISSUE THREAD

**Issue by Megatron2032** [facebookresearch/habitat-api#4]
how can i  integrate habitat and physical env that developed with pybullet

**Comment by msavva** [comment]
Hi @Megatron2032 , thank you for your interest in the Habitat stack.  We are currently working on integration with physics engines (including bullet).  It will be implemented as additional functionality in Habitat-Sim and integrated with Habitat-API in the near future.

**Comment by yashdusing** [comment]
@msavva Hello ! I wanted to ask if there's functionality to somehow stop and start habitat environments on the go. I mean, is it possible to save the context of the current environment and load it at a later time ?

**Comment by msavva** [comment]
Hi @yashdusing , thank you for trying out the Habitat stack.  You can stop and start environments as desired, but we don't currently have an explicit state saving and loading mechanism in the api.  However, you can set the agent state for a particular environment, which coupled with agent state querying can be used to implement the functionality you described.

**Comment by mathfac** [comment]
Closing the issue as the question is answered. Thank you!
