### ISSUE TITLE
Missing(black) areas in the rendered rgb images.

### ISSUE THREAD

**Issue by phongnhhn92** [facebookresearch/habitat-api#402]
## ❓ Questions and Help
Hello, I am rendering a few images from the Matterport dataset by walking the agent around the scene using the  sample_navigable_point function. However, I found that there are a large number of images which have missing or black areas. Is this an error or the rendered images are tend to be that way. If it is rendered that way then why is that ?

Is there any alternative dataset such as Replica that can help me to avoid this problem ?
![rgb](https://user-images.githubusercontent.com/11288381/82049448-011fc280-96bf-11ea-922d-5c7269abc908.png)

**Comment by erikwijmans** [comment]
These are due to holes in the underlying mesh reconstruction -- things are being rendered correctly and fixing holes is an open area of research.  The replica dataset will have considerably fewer of these.
