### ISSUE TITLE
Semantic sensor in Matterport3d captures "void" objects but RGB Depth sensors don't.

### ISSUE THREAD

**Issue by jinlinyi** [facebookresearch/habitat-api#422]
## ❓ Questions and Help
Hi,

I notice Matterport3d meshes have some “void” objects in the mesh (e.g. in the red box), which are not captured by RGB / Depth sensors but will show up in a semantic sensor.
![image (10)](https://user-images.githubusercontent.com/33358154/86389579-8279e700-bc64-11ea-8da3-9fddacd64e56.png)
![image (11)](https://user-images.githubusercontent.com/33358154/86389598-8a398b80-bc64-11ea-89bf-10417c1894e9.png)
I think the issue may be because the semantic sensor reads from the *_semantic.ply while RGB-D sensors read from the *.glb files. The *.glb seems to have cleaned up those "void" objects while the *_semantic.ply still contains those objects. Is there any way to get rid of the "void" objects in semantic image rendering? Thank you!

**Comment by aclegg3** [comment]
Hey @jinlinyi I agree that this problem is a result of the difference between the semantic and RGBD asset geometry. Unfortunately this means there is nothing to be done outside of manually modifying the assets to fix these issues.
