### ISSUE TITLE
What can Habitat do ?

### ISSUE THREAD

**Issue by ulysse-bouchet** [facebookresearch/habitat-api#431]
Hi, I am new to Habitat, and I would like to know what possibilities the API has to offer.
For example, I would like to know how would I use Habitat to do the following : 
- _Going to the bathroom_, movement within the model;
- _Opens the living room window_, interacting with the model;
- _What's the temperature in the kitchen ?_, we assume that there is a temperature sensor in the kitchen and retrieve the current value of the temperature, with artificial values.

I'm thinking of using Habitat for smart home simulation, is it suitable ? 
I'd also like to create my own datasets, is there a way to do it ?

Thank you in advance for your answers.

**Comment by dhruvbatra** [comment]
Welcome. 

Please consider reading the ICCV19 paper linked from our website (https://aihabitat.org/) and README to get an idea of what's possible. 

> Going to the bathroom, movement within the model;
Yes. Consider seeing tasks here: https://aihabitat.org/challenge/2020/

> Opens the living room window, interacting with the model;
Opening windows, no. But rigid-body physics, yes. See
https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html

>  What's the temperature in the kitchen ?, we assume that there is a temperature sensor in the kitchen and retrieve the current value of the temperature, with artificial values.

No.
