### ISSUE TITLE
Confusion about the calculation of SPL

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/habitat-api#444]
## ❓ Questions and Help
Hi, recently I notice there exist some codes with other platforms for navigation(e.g., AI2-THOR). When they calculate SPL, the length of the path is the number of steps rather than the Euclidean distance. 

Is that reasonable in navigation tasks? For example, if the agent keeps spinning, the Euclidean distance won't increase.

If I misunderstand this, please tell me. Thanks a lot.

**Comment by dhruvbatra** [comment]
Please read Section 2.1.1 here: https://arxiv.org/abs/2006.13171
