### ISSUE TITLE
Is random exploration possible?

### ISSUE THREAD

**Issue by qmaruf** [facebookresearch/habitat-api#446]
## ❓ Questions and Help

Is it possible to perform random exploration in a scene? I want to move the agent into all free spaces and collect semantic and depth information.

Currently, I am using `examples/shortest_path_follower_example.py ` to move the agent from point `A` to `B`. As expected it takes the shortest path. Though I can use multiple episode to explore the scene, it doesn't guarantee that the agent will explore all available free space.

Is there any API avaialbe to move the agent in all free spaces?

**Comment by dhruvbatra** [comment]
Have you read the documentation here? 
http://aihabitat.org/docs/habitat-api/habitat-api-demo.html
http://aihabitat.org/docs/habitat-sim/image-extractor.html
