### ISSUE TITLE
Semantic mask of an desired object which includes the occluded parts 

### ISSUE THREAD

**Issue by eric-xw** [facebookresearch/habitat-api#58]
It would be very useful if the API can support a function that provides the semantic mask of an object at a specific view, including both its visible and occluded parts.  

It can further enable various tasks related to computer vision like amodal recognision/detection.

**Comment by erikwijmans** [comment]
Can you open this as a feature request on https://github.com/facebookresearch/habitat-sim.  That is something we'd need to do on the simulator side

**Comment by eric-xw** [comment]
ok. np.
