### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by koriavinash1** [facebookresearch/habitat-api#62]
Can anyone please help me in understanding the difference between 'pointgoal' in observation and self._env.current_episode.goals? 
observation['pointgoal'] \in R^2 while target_goals \in R^3, what are each of them?

**Comment by erikwijmans** [comment]
The goal in `current_episode.goals` is the 3D position of the point goal in _world_ coordinates.  The 2D pointgoal observation is  the 2D position of the point goal in the agent's _egocentric_ coordinates (by default, this is also converted to polar coordinates as that leads to much simpler hand-coded logic).

So `observation['pointgoal']  = xyz_to_2d_polar(R_agent_world * (current_episode.goals[0] - agent.position))`.  See the code here: https://github.com/facebookresearch/habitat-api/blob/master/habitat/tasks/nav/nav_task.py#L181
