### ISSUE TITLE
Mistake in Agent class' docs

### ISSUE THREAD

**Issue by titardrew** [facebookresearch/habitat-api#65]
Agent's class docs string states that user has to implement 2 methods: `reset` and `step`. However, If I understood correctly, there's no method named `step` and there is method `act` instead. This is quite tiny issue but still.
https://github.com/facebookresearch/habitat-api/blob/c7443c39c5186e517d8a4b7c87a1b42106e4e77a/habitat/core/agent.py#L10-L17

**Comment by abhiskk** [comment]
Thanks for catching this @titardrew
