### ISSUE TITLE
Incorrect render() method in VectorEnv class.

### ISSUE THREAD

**Issue by titardrew** [facebookresearch/habitat-api#70]
https://github.com/facebookresearch/habitat-api/blob/8c5329ce9f777395b45c2daac135377e629ec148/habitat/core/vector_env.py#L313-L331
In this function you send tuple 
```python
(args, {"mode": "rgb_array", **kwargs})
``` 
However, it does not contain command index that you want to be executed by worker. Furthermore, your environments do not have ```rgb_array``` mode of rendering, they use ```rgb``` instead. This makes ```render()``` incorrect.
I think you have to replace line with ```write_fn``` call with:
```python
write_fn( (RENDER_COMMAND, (args, {"mode": "rgb", **kwargs})) )
```

**Comment by abhiskk** [comment]
Thanks for catching this @titardrew, the `rgb_array` usage is legacy code and should have been updated, if possible can you send a PR for making this change?
